using System;

namespace GuessNumberNew
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Guess a number program - C# Assigment 7");
            Console.WriteLine("---------------------------------------");

            //Declarations
            int hidden = 0, userNum, passFlag;
            bool found = true, skipCheck = false;
            int cntGuessesValid = 0, cntEntries = 0, hldGuesses = 0;
            string promptMsg;

            passFlag = 0; // first run
            promptMsg = "Hey You! Guess a number between 1 and 100. Type 0 to quit... ";

            do
            {
                //get random number from computer
                if (found)
                {
                    hidden = RandomNumber(1, 100);
                    cntGuessesValid = 0;
                }

                do
                {
                    cntEntries++;
                    userNum = PlayGame(promptMsg, passFlag);
                    if (userNum == 0) { cntGuessesValid--; skipCheck = true; break; }
                } while (userNum < 1 || userNum > 100);

                cntGuessesValid++;

                // user is playing
                if (!skipCheck)
                {
                    // keep guessing until they guess the number
                    if (userNum != hidden)
                    {
                        found = false;
                        hldGuesses = cntGuessesValid;
                        if (userNum > hidden)
                        {
                            Console.WriteLine("Your number " + userNum + " is too high.");
                        }
                        else
                        {
                            Console.WriteLine("Your number " + userNum + " is too low.");
                        }
                    }
                    else
                    {
                        found = true;
                        hldGuesses = cntGuessesValid;
                        Console.WriteLine("");
                        Console.WriteLine("You are a WINNER !!! Your number " + userNum + " matches random number " + hidden);
                        userNum = 0;
                    }
                    promptMsg = "Type another number between 1 and 100. Type 0 or Q to quit... ";
                    passFlag = 1;
                }
            } while (userNum > 0);

            if (cntGuessesValid > 0)
            {
                Console.WriteLine("");
                Console.WriteLine("Number of valid guesses you have made is: " + hldGuesses);
                if (!found)
                {
                    Console.WriteLine("The random number generated by the comoputer was " + hidden);
                    Console.WriteLine("Good bye!!!");
                }
                Console.WriteLine("Type any key to exit...");
                Console.ReadLine();
            }
        }

        private static int RandomNumber(int min, int max)
        {
            Random random = new Random();
            return random.Next(min, max);
        }

        private static bool ReturnUserAnswerToQuit(string userAnswer)
        {
            if (userAnswer.ToUpper().Trim() == "Q") return true;
            return false;
        }

        private static int ReturnUserNumber(string promptUser, int flag)
        {
            int nUser;
            string userAns;

            // ask user for a number
            Console.Write(promptUser);
            while (!Int32.TryParse(userAns = Console.ReadLine(), out nUser))
            {
                if (ReturnUserAnswerToQuit(userAns))
                {
                    if (flag == 1 && nUser == 0) { break; }
                }
                Console.Write(promptUser);
            }
            return nUser;
        }

        private static int PlayGame(string prompt, int flag)
        {
            int playNum = 0;

            if (flag == 1)
            {
                Console.Write(prompt);
                if (Int32.TryParse(Console.ReadLine(), out playNum))
                {
                    // zero is a valid entry because '0' is used to quit 
                    if (playNum < 0 || playNum > 100) { playNum = ReturnUserNumber(prompt, flag); }
                }
                else
                {
                    if (ReturnUserAnswerToQuit(playNum.ToString())) { playNum = 0; }
                    else { playNum = ReturnUserNumber(prompt, flag); }
                }
            }
            else { playNum = ReturnUserNumber(prompt, flag); }

            return playNum;
        }
    }
}
